### PR TITLE
https://github.com/GluuFederation/oxAuth/issues/796

### PR DESCRIPTION
**Pull request by syntrydy**

### CODE REVIEW

**Comment by syntrydy** [comment]
Fixed

**Comment by yuriyz** [comment]
@syntrydy please do not re-format all code because it is not clear what did you change. Check format settings of your IDE.

**Comment by yurem** [comment]
@syntrydy There is no easy way to review your changes. Please, don't change variable names and formatting. As far as I find you fixed only one statement here:
image

Also in most places we uses `log` instead of `logger`.

**Comment by yurem** [comment]
Also due to formatting changes we got problems during merging it in 3.1.x.
Please create new PR with fixes only.

**Pull request merged**
