### PR TITLE
Update home.xhtml

### PR DESCRIPTION
**Pull request by syntrydy**
https://github.com/GluuFederation/oxAuth/issues/765

### CODE REVIEW

**Comment by willow9886** [comment]
@yurem can you take a look at this quickly?

**Comment by willow9886** [comment]
based on this community ticket: https://support.gluu.org/access-management/5223/in-oxauth-rp-the-authorization-code-is-not-copied-into-the-code-input-field-of-the-token-endpoint-section/#at31120

**Comment by yurem** [comment]
It works fine when we request 'code':
```
Sample response:
https://u144.gluu.info/oxauth-rp/home.htm?code=51b501aa-2674-4e5b-af2c-ec97608be9c5&scope=address+openid&session_id=d5f71ac4-5d49-454f-b889-c7146f4a52b4&state=xyz&session_state=6ad146db-2c39-4ae5-bbb7-1ec849e5432c
```

But it not works with this:
```
Sample response:
https://u144.gluu.info/oxauth-rp/home.htm#access_token=c020d4b4-a9a0-4a40-b983-1cee90bb37cc&scope=address+openid&session_id=a2bfde01-0794-41e7-a8bb-1157a59234eb&state=xyz&token_type=bearer&session_state=ae65d085-cf0c-4889-a7b2-07bfa67e7e57&expires_in=299
```

**Comment by yurem** [comment]
Can you try [fixed](https://github.com/GluuFederation/oxAuth/blob/master/RP/src/main/webapp/home.xhtml#L926) home.xhtml?

**Pull request closed without merging**
