### PR TITLE
oxCore#44

### PR DESCRIPTION
**Pull request by rajnikantsh**
Added Support for checkstyle plugin in maven.

### CODE REVIEW

**Comment by yuriyz** [comment]
@rajnikantsh I don't see `checkstyle.xml`, how can we configure style without it ?

**Comment by rajnikantsh** [comment]
@yuriyz Maven check style plugin is by default sun_checks.xml. If there is any customized  formatting you need Please let me know. I can create checkstyle.xml according to that.

**Comment by yuriyz** [comment]
@rajnikantsh I see, where I can find that `sun_checks.xml` ? It would be nice to take a look what is inside it.

**Comment by rajnikantsh** [comment]
@yuriyz  I have comitted file checkstyle.xml just copied the content of sun_checks.xml.

**Comment by yuriyz** [comment]
@rajnikantsh I propose to split it from `oxauth`. We have many java projects and it is good idea to share `checkstyle.xml` among those projects instead of copy/pasting. Maybe better to use `community-edition-setup` and then share resources among the projects (e.g. `oxcore`, `oxd`, `oxtrust` ). 

http://blog.sonatype.com/2008/04/how-to-share-resources-across-projects-in-maven/

**Comment by rajnikantsh** [comment]
@yuriyz  Sure I will make sure to share common configuration for all projects.

**Comment by yuriyz** [comment]
If we really want to apply checkstyle then we have to start from oxCore and then re-use. We don't want `checkstyle.xml` in oxauth project.

**Pull request closed without merging**
