### PR TITLE
Whispeak open integration

### PR DESCRIPTION
**Pull request by Whispeak-io-VoiceBiometrics**
Hi,

This is our first contribution to upstream Gluu from Whispeak, http://whispeak.io/.

Following is the script to authenticate via voice that we use internally, which has many customizations in order to purpose directly enrollment with an optional third party OIDC verification and fallback mechanisms.

We are changing some of the root resources of Gluu as for example localization but we did not found any alternative to have these resources local to the script other than full Javascript which will be to add quite a lot of extra logic. Regarding CSS and JS we have also added in standard locations following the example of other scripts.

All is integrated in the same script for maintainability reasons, but if it's too broad we can do simpler versions of it. We would also like to explore CASA integrations in order to connect multiple scripts but we don't have the time nor the resources to do that at the moment.

There are some questions that we would like to discuss as how to check user's password without authenticating him so to have a more secure authentication in two steps. We have included a draft here that calls "authenticate" from "AuthenticationService" bean before all tests are done, which is not ideal.

We're not Gluu specialists, so of course feel free to do any recommendations or even change the script to adapt to best practices.

Best regards,

_______________________________________________________________________________
Vreixo Gonzalez
Whispeak - CTO
vgonzalez@whispeak.io
www.whispeak.io
165 Avenue de Bretagne
Whispeak, Étage 3, Porte 1
59000 Lille

### CODE REVIEW

**Comment by yurem** [comment]
Thank for sharing this code with us. This PR looks good. I've made review. I only have question about how you use `cache` ([CacheService](https://github.com/GluuFederation/oxCore/blob/master/core-cache/src/main/java/org/gluu/service/CacheService.java#L20)). This is application scoped service. In your code you use static keys. As result this might led to issues when more than one user will do login in parallel. You can use for example `session_id` to append to your keys. In `authenticate` and `prepareForStep` you can get it from identity: `identity.getSessionId(0.getId()`.

Why you store some parameters in `identity.setWorkingParameter` while other in `cache`? `Authenticator` automatically persist and restore from session all parameters which script set in `identity` at each authentication step. You only need to add required parameters to list which `getExtraParametersForStep` returns.

**Comment by nynymike** [comment]
Perhaps what we should do is add some `TODO` items into the script and publish it, because it is a third party script, not core code.

**Comment by yurem** [comment]
Hi

> We do need to use workingParameter as we need them for the xhtml templates but indeed we could put everything dependent on the session there instead of indexing by session id the cache. Or there would be any advantages on using the cache?

It's better to use workingParameter if you need to store data related to specific user login. In this case you will get performance benefits because application persist all workingParameter together in one DB transaction. While each cache operation application execute immediately.


> Regarding the cache, we guess that is better to keep in there the information not changing in between sessions, like the parameters of the script? We perform some checks over them, so is useful for us to keep them stored once processed. By the way, we plan moving some of these checks to init so to avoid performing them on every session, is it ok to use cache in "init" function?

Yes, it's ok to use `cache` in init function. In this case other instances in cluster can reuse same data at startup. But, please, keep in mind that cache objects have expiration `public void put(int expirationInSeconds, String key, Object object)`.
If needed you can store script data in global python variables. oxAuth uses one instance of script and reloads it only on script update.

**Comment by yurem** [comment]
> Perhaps what we should do is add some `TODO` items into the script and publish it, because it is a third party script, not core code.

Yes, we can merge it right now. And apply small changes later.

**Comment by Whispeak-io-VoiceBiometrics** [comment]
Thanks for the remarks, we are currently using global variables and workingParameters. Regarding the last part of my original message, there is the possibility of checking the password without authenticating the user?

Seeing the code it seems to already perform some authentication success logic the "authenticate" function from "Authentication" service if password is correct even if not all the steps of the scripts are validated.

Thank you very much

**Review by yurem — APPROVED** [review]

**Pull request merged**
