### PR TITLE
Support for SMPP 2FA

### PR DESCRIPTION
**Pull request by norox**
Support for SMPP 2FA, it works the same way as Twilio but uses a SMPP server instead.
Sorry for all the changes in some of the translation files, my IDE (NetBeans) did that automatically.

### CODE REVIEW

**Comment by jgomer2001** [comment]
hi @norox , thanks for your interest in contributing to CE. Unfortunately it is not clear how we can test your work (it looks fine) but we need instructions on how to setup. This is very important because in the end your target is Casa.

- From what I see there are several config params like `smpp_server`, `smpp_port`, etc. What kind of values go there?  is there a ready-to-use free server for this or do we have to setup one? that will require time and some guidance from your side
- The script has external dependencies, can you list the jar  files needed?
- I didn't like the changes to resource bundle files either, can you revert those and update the PR :) ?

**Comment by norox** [comment]
Hi jgomer2001,

> hi @norox , thanks for your interest in contributing to CE. Unfortunately it is not clear how we can test your work (it looks fine) so we need instructions on how to setup. This is very important because in the end your target is Casa.
> 
> * From what I see there are several config params like `smpp_server`, `smpp_port`, etc. What kind of values go there?  is there a ready-to-use free server for this or do we have to setup one? that will require time and some guidance from your side

 - smpp_server: IP or FQDN of SMPP server (string).
 - smpp_port: TCP port of the SMPP server (int).

system_id and password are only used if authentication is required.
 - system_id: username (called system_id in SMPP) (string).
 - password: password (string)

The settings below should only be changed if specified by the SMPP service provider.
Valid values for TON: https://jar-download.com/javaDoc/org.jsmpp/jsmpp/2.3.2/org/jsmpp/bean/TypeOfNumber.html
Valid values for NPI: https://jar-download.com/javaDoc/org.jsmpp/jsmpp/2.3.2/org/jsmpp/bean/NumberingPlanIndicator.html

 - source_addr_ton: Type of number (default: ALPHANUMERIC)
 - source_addr_npi: Numbering plan indicator (default: ISDN)
 - source_addr: From number / name, allowed values depends on source_addr_ton (default: Gluu OTP)
 - dest_addr_ton: Type of number (default: INTERNATIONAL)
 - dest_addr_npi: Numbering plan indicator (default: ISDN)

To my knowledge there is no free SMPP service provider, but there are plenty of SMPP providers, we use our own SMPP server.
There was a SMPP simulator called SMPPSim but it's no longer in development and unavailable.

> * The script has external dependencies, can you list the jar  files needed?

Only jsmpp:
  <dependency>
    <groupId>org.jsmpp</groupId>
    <artifactId>jsmpp</artifactId>
    <version>2.3.7</version>
  </dependency>

> * I didn't like the changes to resource bundle files either, can you revert those and update the PR :) ?

Fixed

**Comment by jgomer2001** [comment]
Thanks @norox , I'm going to merge your changes soon. Right now we are about to release CE4.0 and no commits are allowed except for bug fixing.

**Comment by jgomer2001** [comment]
pending making  SMPP script part of community-edition-setup

**Pull request merged**
