### PR TITLE
Issue 307

### PR DESCRIPTION
**Pull request by worm333**
This pull request refers to issue #307.  Before merging it, there is need to be convinced that [activemq](http://activemq.apache.org/) is added as a new gluu component.

### CODE REVIEW

**Comment by yurem** [comment]
This code track next activities:
CLIENT_REGISTRATION("CLIENT_REGISTRATION"),
CLIENT_UPDATE("CLIENT_UPDATE"),
CLIENT_READ("CLIENT_READ"),
CLIENT_DELETE("CLIENT_DELETE"),
USER_AUTHORIZATION("USER_AUTHORIZATION"),
USER_INFO("USER_INFO"),
TOKEN_REQUEST("TOKEN_REQUEST"),
TOKEN_VALIDATE("TOKEN_VALIDATE");

I think we should also track:
TOKEN_INVALIDATE -- expiration and from end_session endpoint
SESSION_UNATHENTICATED -- to track login sessions
SESSION_AUTHENTICATION -- after user authentication
SESSION_DESTROY -- session expiration or end_session call

**Comment by worm333** [comment]
> I've 2 questions about OAuth2AuditLogger:
1) Is sendMessage method ThreadSafe?
2) We need to add annotation @Asynchronous to avoid oxAuth delay needed to send JMS message

1. Good catch! Indeed Session object does not support usage by concurrent threads, therefore all objects created from that Session instance are not thread safe too. I will make the necessary changes to ensure that OAuth2AuditLogger is thread safe.


2. ActiveMQ [supports](http://activemq.apache.org/async-sends.html) sending messages in async mode and we can easily activate it. How do you think which way is better suited for us: use `@Asynchronous` annotation or the way provided by ActiveMQ?

> We should not hardcode: localhost:61616 It should be configurable to use central JMS server in cluster

Does adding:
```
private String jmsHost;
private int jmsPort;
```
in `org.xdi.oxauth.model.configuration.Configuration` would be a good idea ?

**Comment by yurem** [comment]
Maybe it's better to add comma separated list?
server1:61616, server2:61616

**Comment by yurem** [comment]
Regarding <b>@Asynchronous</b>... I prefer to use together EJB + ActiveMQ. Adding @Asynchronous to method will make Seam/EJB independent from method implementation. Also Seam will reuse one instance in all calls because it's application scope component. We also can use ActiveMQ async sending too. This should improve performance on multi CPU machines. Final design will be next:

Application call:

```
oAuth2AuditLogger.sendMessage(oAuth2AuditLog);
```

and continue work without waiting for message delivery.

In same time ActiveMQ sending messages in async mode to server which allow to not less memory on client to hold messages in queue, etc...

What do you think? Should we use both async approaches.

**Comment by yurem** [comment]
I think something wrong with this branch. It contains other commits from master... I think we can try to create new branch from master. And use jerry-pick to put into it only required changes related to this issue. Ping me on Monday, I will help to do this.

**Comment by worm333** [comment]
Replace this pull request with [another one](https://github.com/GluuFederation/oxAuth/pull/368)

**Pull request closed without merging**
