### PR TITLE
Added system config to enable/disable CIBA functionalities.

### PR DESCRIPTION
**Pull request by miltonbo**
Related to issue: #1404

Successful Jenkins execution with these changes: https://ox.gluu.org/jenkins/job/oxAuth_master_LDAP/1103

### CODE REVIEW

**Comment by yuriyz** [comment]
cibaEnabled is internal oxauth configuration property. Shouldn't it be inside `AppConfiguration`?

**Comment by miltonbo** [comment]
Well, the requirement was that I have to add a new flag like these others:

image

That config is managed in `ou=configuration,o=gluu`, that's why I added the flag in that part as others.

image

**Comment by yuriyz** [comment]
It's not system property. It's oxauth property.

**Comment by miltonbo** [comment]
In `ciba` channel this was proposed by @yurem and as you can see in the screenshot, it says `System Configuration`, initially I implemented `oxAuth` part, however we will use it in `oxTrust` also and all those parameters are in `ou=configuration`. Anyway, if @yurem doesn't have any issue with that, I would proceed changing that implementation.

**Comment by miltonbo** [comment]
@yuriyz please, take a look to my PR, based on the suggestion, I changed it to use a json property.

Jenkins build: https://ox.gluu.org/jenkins/job/oxAuth_master_LDAP/1183

**Pull request merged**
