### PR TITLE
fix oidc session change detection

### PR DESCRIPTION
**Pull request by livetocode**
Hi,

I've spent a lot of time researching issues related to oidc session change detection as it was not properly working with Gluu 3.1.6 and later.

I've discussed my research and provided a complete bug report in the following repo https://github.com/livetocode/gluu-oxauth-bug-report-01, which also includes sample projects for reproducing the issues.

I don't know if this PR is the final solution to the reported issues but at least I managed to get it working with very few changes.

Hope this helps,

Morgan Martinet

### CODE REVIEW

**Comment by livetocode** [comment]
I've also submitted a bug report in your issue tracker:
https://support.gluu.org/single-sign-on/7650/oidc-session-change-detection-issues/

**Comment by livetocode** [comment]
Hi there!
Any feedback so far? It's been 4 days ;-)
bye

**Comment by willow9886** [comment]
Hi, sorry for the delay. Our colleague has been out sick the last few days. We will review as soon as he's back. Thanks for the contribution.

**Comment by livetocode** [comment]
Oh! Sorry! Wish him a good recovery!

**Comment by livetocode** [comment]
Hi! Just pinging to check if there was any progress on this PR?
I can tell that we've been testing it in staging for a month and that we are in prod for a week.

**Comment by yurem** [comment]
Hi! I quickly review your PR and documentation already one week ago. For impression that it's very good. I'm planning to check the code and merge it at Friday

**Comment by livetocode** [comment]
Ok, great! Don't hesitate to ask me any question.

**Comment by yurem** [comment]
`rp_origin_id` is our custom error handling implementation. It works only when `errorHandlingMethod = remote`.
It's needed for case when `id_token` was expired or user clicked end session 2 times. Instead of showing error page oxAuth redirect user to RP to handle this error properly.

We added this to resolve customer request to not show error page on end_session call.

**Comment by livetocode** [comment]
Thanks for merging the PR!

For rp_origin_id, I guess that you really need the cookie because the session does not exist in Gluu any more?

Also, what about the session_state cookie? Is it still needed or was it replaced with the obps cookie?

**Comment by yurem** [comment]
Thank you for PR!

Yes, you are right about `rp_origin_id` cookie.

@yuriyz @qbert2k can you answer about `session_state` cookie?

**Comment by yuriyz** [comment]
I think we still need it. The scope of `opbs` and `session_state` is different. 
From spec `opbs` - `It captures meaningful events such as logins, logouts, change of user, change of authentication status for Clients being used by the End-User, etc. `
`session_state` - `in addition to the browser state, incorporate sufficient randomness in the form of a salt`.

**Pull request merged**
