### PR TITLE
Client Grant Type configurations

### PR DESCRIPTION
**Pull request by rajnikantsh**

### CODE REVIEW

**Comment by nynymike** [comment]
Resolves https://github.com/GluuFederation/oxAuth/issues/527 and https://github.com/GluuFederation/oxAuth/issues/526

**Comment by nynymike** [comment]
1. Has https://github.com/GluuFederation/community-edition-setup been updated so this property will be present initially?
2. Have the docs been updated so that this new property is reflected in the reference section

**Comment by rajnikantsh** [comment]
Yes, an individual pull request is made in community-edition-setup and docs projects corresponding to this change

**Comment by yurem** [comment]
I have 2 questions for this request:
1) Restriction to list of allowed grant types works only if enableClientGrantUpdate=true
2) Also there is no restriction to dynamic_client_reg_default_grant_type in client registration method. The restriction works only in update method.

Please create 2 separated pull requests for each issue. It will help to review issues.

**Comment by rajnikantsh** [comment]
1. Yes restrictions will only work if enableClientGrantUpdate=true. And
2. Yes this restriction only works during update method.

I created two separate pull request for oxAuth#526 and oxAuth#527.

**Pull request merged**
