### PR TITLE
Issue 283

### PR DESCRIPTION
**Pull request by worm333**
Issue #283: created log4j appender to add mac address into the logs.

### CODE REVIEW

**Comment by worm333** [comment]
Here is sample log:
```
2016-11-11 13:21:05,127 TRACE [org.xdi.oxauth.service.AttributeService] MAC Address: 98-11-27-AA-F0-FE
Get attribute from cache by Dn 'inum=@!EAD1.7801.B268.92FD!0001!500A.EF2B!0005!8F88,ou=attributes,o=@!EAD1.7801.B268.92FD!0001!500A.EF2B,o=gluu'
```

**Comment by nynymike** [comment]
Why is this log message on two lines? If you are grepping for the MAC address, it wouldn't show the log message.

**Comment by worm333** [comment]
I've changed format, so the MAC address and the log message are on the same line now:
```
2016-11-29 22:26:01,469 INFO  [org.jboss.seam.servlet.SeamFilter] MAC Address: A0-99-9B-01-11-C9. Initializing filter: org.jboss.seam.web.redirectFilter
```

**Comment by yurem** [comment]
I offer to make it customable. We should not log MAC by default. To enable this we need to specify in appender section:
        <param name="LogMac" value="true"/>

**Comment by worm333** [comment]
Replacing this pull request with [another one](https://github.com/GluuFederation/oxAuth/pull/380).

**Pull request closed without merging**
